#BingoBotConfig.py is in .gitignore because it exposes user authentication data.
#This is a dummy file for demonstration only.

group_id = 1234567890 #group_id (aka feed_id in URL) as int
access_token = '12345-a72jD2kf9KWDkad1OAd0' #"developer token" generated by Yammer client registration portal
